---
format: html
toc: false
---

<h1 style="font-size: 3em;">Build data apps in minutes, <br>click by click.</h1>

Build apps using a web-based point and click user interface. No coding experience required.

<div class="mt-4 mb-5" style="text-align: left;">
  <a href="tutorials/01-getting-started.qmd" class="btn btn-primary btn-lg" role="button" style="width: 180px;">Get started</a>
  <a href="https://blockr.cloud" class="btn btn-outline-secondary btn-lg ms-2" target="_blank" role="button" style="width: 180px;">Try in the cloud</a>
</div>

{{< video https://www.youtube.com/watch?v=_j0dOkGrkew >}}

## How does it work?

Data analyses can be broken down into fundamental units, here called blocks, such as loading, transforming, or visualising data.
Simply add the blocks to the canvas, connect them, and watch blockr automatically run the pipelines.

## Share your work

Want to share your analyses as an interactive dashboards?
Blockr ships with a clever grid-based system, allowing you to drag and drop the contents of your blocks wherever you like.
Toggle parts of your block on and off to control what your users see.

## Who is it for?
blockr is designed for anyone who works with data:

- **Analysts** who want to quickly explore data without writing code
- **Researchers** who need reproducible workflows
- **Teams** who want to share and collaborate on data pipelines

## Reproducible
Every blockr application can generate reproducible R code to recreate your analysis outside of blockr.
This ensures portability and reproducibility, making it easy to switch tools, collaborate across multidisciplinary teams, and bring scientific rigor to your work.


## Extensible and open-source

blockr is built on top of R and was designed with extensibility in mind.
It provides a set of tools and API's to allow developers to create their own custom blocks and extend the framework.

blockr is open-source and is released under a GPL-3 [license](https://github.com/BristolMyersSquibb/blockr?tab=GPL-3.0-1-ov-file#readme).
 
## How to read these docs

These documents are _user_-facing and not _developer_-facing.
They will teach you how to _use_ blockr, not how to _develop_ it.
If you are looking for developer docs, start [here](https://bristolmyerssquibb.github.io/blockr.core/).

The documentation is split into four parts:

::: {.grid}

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100}
::: {.card-body .text-center}
<i class="bi bi-mortarboard" style="font-size: 3rem;"></i>

### Tutorials

Learn by doing with step-by-step tutorials that walk you through practical examples.

[To the tutorials](tutorials/01-getting-started.qmd){.btn .btn-primary .w-100}
:::
:::
:::

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100}
::: {.card-body .text-center}
<i class="bi bi-signpost-2" style="font-size: 3rem;"></i>

### How-To's

Reach a specific goal with focused guides for common tasks.

[To the how-to's](howto/index.qmd){.btn .btn-primary .w-100}
:::
:::
:::

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100}
::: {.card-body .text-center}
<i class="bi bi-book" style="font-size: 3rem;"></i>

### Fundamentals

Broaden your understanding with in-depth explanations of key concepts.

[To the fundamentals](fundamentals/index.qmd){.btn .btn-primary .w-100}
:::
:::
:::

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100}
::: {.card-body .text-center}
<i class="bi bi-braces" style="font-size: 3rem;"></i>

### Reference

Lookup a block with detailed specifications and parameters.

[To the reference](reference/index.qmd){.btn .btn-primary .w-100}
:::
:::
:::

:::
